# General configuration
media: assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: author, type: string, label: Author }
      - { name: date, label: Date, type: date }
      - { name: categories, type: string, label: Categories }
      - { name: tags, type: string, label: Tags }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }

  - name: pdfs
    label: PDFs
    type: collection
    path: assets/issues
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: file, label: PDF File, type: file }
